# Generated by Django 5.1.4 on 2024-12-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0004_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(upload_to='staff_photos/'),
        ),
    ]
