# Generated by Django 5.1.4 on 2024-12-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0005_alter_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mname',
            field=models.CharField(blank=True, max_length=144, null=True),
        ),
    ]
