# Generated by Django 5.1.4 on 2025-01-21 09:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('chemical_formula', models.CharField(max_length=100)),
                ('cas_number', models.CharField(max_length=50, unique=True)),
                ('quantity', models.FloatField()),
                ('purchase_date', models.DateField()),
                ('unit', models.CharField(choices=[('g', 'Grams'), ('ml', 'Milliliters'), ('l', 'Liters'), ('kg', 'Kilograms')], max_length=2)),
                ('storage_location', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('hazard_level', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], max_length=1)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='duser')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model_number', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('purchase_date', models.DateField()),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AV', 'Available'), ('IM', 'In Maintenance'), ('BR', 'Broken'), ('RS', 'Reserved')], default='AV', max_length=2)),
                ('notes', models.TextField(blank=True)),
                ('quantity', models.IntegerField()),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='cuser')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_return_date', models.DateTimeField()),
                ('actual_return_date', models.DateTimeField(blank=True, null=True)),
                ('purpose', models.TextField()),
                ('destination', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('CO', 'Checked Out'), ('RT', 'Returned'), ('OD', 'Overdue')], default='CO', max_length=2)),
                ('condition_on_checkout', models.TextField()),
                ('condition_on_return', models.TextField(blank=True, null=True)),
                ('checked_out_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scilab.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PL', 'Planned'), ('IP', 'In Progress'), ('CM', 'Completed'), ('HL', 'On Hold')], default='PL', max_length=2)),
                ('results', models.TextField(blank=True)),
                ('chemicals_used', models.ManyToManyField(to='scilab.chemical')),
                ('equipment_used', models.ManyToManyField(to='scilab.equipment')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
